name: first_page
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  freezed_annotation: ^3.1.0
  jaspr: ^0.21.6
  jaspr_router: ^0.7.3
  riverpod: ^3.0.3
  

dev_dependencies:
  build_runner: ^2.10.1
  jaspr_web_compilers: ^4.3.2+1
  jaspr_builder: ^0.21.6
  jaspr_lints: ^0.5.1
  lints: ^5.0.0
  freezed: ^3.2.3

jaspr:
  mode: server

